### ISSUE TITLE
Problem with connection with MongoDB

### ISSUE THREAD

**Issue by jx-nin** [Hack-Weekly/sage-giraffe-todo#5]
After 45-60 seconds after connecting with DB, it throws an error:

```
[1] Connected to MongoDB
[1] /home/jxnin/Pulpit/sage-giraffe-todo/backend/node_modules/mongoose/lib/connection.js:755
[1]     err = new ServerSelectionError();
[1]           ^
[1] 
[1] MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
[1]     at _handleConnectionErrors (/home/jxnin/Pulpit/sage-giraffe-todo/backend/node_modules/mongoose/lib/connection.js:755:11)
[1]     at NativeConnection.openUri (/home/jxnin/Pulpit/sage-giraffe-todo/backend/node_modules/mongoose/lib/connection.js:730:11) {
[1]   reason: TopologyDescription {
[1]     type: 'Unknown',
[1]     servers: Map(1) {
[1]       'localhost:27017' => ServerDescription {
[1]         address: 'localhost:27017',
[1]         type: 'Unknown',
[1]         hosts: [],
[1]         passives: [],
[1]         arbiters: [],
[1]         tags: {},
[1]         minWireVersion: 0,
[1]         maxWireVersion: 0,
[1]         roundTripTime: -1,
[1]         lastUpdateTime: 201833,
[1]         lastWriteDate: 0,
[1]         error: MongoNetworkError: connect ECONNREFUSED ::1:27017
[1]             at connectionFailureError (/home/jxnin/Pulpit/sage-giraffe-todo/backend/node_modules/mongodb/lib/cmap/connect.js:383:20)
[1]             at Socket.<anonymous> (/home/jxnin/Pulpit/sage-giraffe-todo/backend/node_modules/mongodb/lib/cmap/connect.js:307:22)
[1]             at Object.onceWrapper (node:events:628:26)
[1]             at Socket.emit (node:events:513:28)
[1]             at emitErrorNT (node:internal/streams/destroy:151:8)
[1]             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[1]             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[1]           cause: Error: connect ECONNREFUSED ::1:27017
[1]               at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
[1]             errno: -111,
[1]             code: 'ECONNREFUSED',
[1]             syscall: 'connect',
[1]             address: '::1',
[1]             port: 27017
[1]           },
[1]           [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
[1]         },
[1]         topologyVersion: null,
[1]         setName: null,
[1]         setVersion: null,
[1]         electionId: null,
[1]         logicalSessionTimeoutMinutes: null,
[1]         primary: null,
[1]         me: null,
[1]         '$clusterTime': null
[1]       }
[1]     },
[1]     stale: false,
[1]     compatible: true,
[1]     heartbeatFrequencyMS: 10000,
[1]     localThresholdMS: 15,
[1]     setName: null,
[1]     maxElectionId: null,
[1]     maxSetVersion: null,
[1]     commonWireVersion: 0,
[1]     logicalSessionTimeoutMinutes: null
[1]   },
[1]   code: undefined
[1] }
[1] 
[1] Node.js v18.12.1
```

**Comment by ahmedmaher2481998** [comment]
i fixed this ,  the issue was that env wasn't loading you have to make call.config before using any env vars in any file, also i added .env.example, run this command, then open the copied file “.env” and fill the Var name with the right ones.
`cp .env.example .env`
